[Variables]
; --- GENERAL ---
FontName=SF Pro - Stencil
; FontName=OnePlus Sans Display Medium ; Or use a system font if you prefer

UpdateRate=1000 ; How often the skin updates in milliseconds (1000 = 1 second)

; --- COLORS ---
Color1=255,255,255,255 ; Main text color (White, slightly transparent)
Color2=235,87,87,255 ; Secondary text color (Slightly more transparent white)
ColorAccent=235,87,87,255 ; Accent color (OnePlus Red)

; --- SIZES ---
SizeClock=125
SizeDate=41

; --- MODE ---
DisplayStyle=Gradient

; --- GRADIENT SETTINGS ---
GradientAngle=0
GradientColorStart=0,150,255,220
GradientColorEnd=200,0,255,220
GradientRedStart=255,0,0,255
GradientRedEnd=255,100,100,255
